export const LOAD_DONATIONS_FROM_SERVER = 1000
export const LOAD_DONATORS_FROM_SERVER = 1001;
export const UPDATE_DONATORS = 1002;
export const UPDATE_DONATIONS = 1003;

export const LOAD_STORIES_FROM_SERVER = 2000;
export const UPDATE_STORY_IN_SERVER = 2001;
